apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
spec:
  interval: 10m
  path: ./network/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: network
