apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: <TA_STORAGE_CLASS>
