apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PX4/skZtZX1aRofbzszy2gNpJsayi3pCbfH/xF7aRi1kl7pD33h/Fw==,iv:M9J1ew4MPnXIhIo1DjUZwGA4UudZFp+D4fSfL0+l2jA=,tag:iDeCWRlBir+zAORfwJ7Sfw==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT0VDSnhoS2laZ0M5RlN2
        a2JtOFJhNW1wMmZzNHJPMlg0ODVCaFZTUVRrCmxyYkVUN1FpbEg4OSsxS1ZWcDJy
        RndMVEpMRTl1TXc1bFN3cW9HamFnLzgKLS0tIGtOSkhkUDA0ZmF1cEdXcDRHdk1V
        emZDREJrVHYrR3FESW5EUnBjenEzM28KzTlTN5Gv8xyS65QRofK8ie4CdrV7v1hT
        3iMyjMMnlkI9lvOU5HUF6yBo5PGPSggAQwvVqo08pY6QJSEYaCpB/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T20:32:34Z"
  mac: ENC[AES256_GCM,data:XuYoMsRz78kEoyqUUSyNH63bc2dZZ1zzG7CgI10b5zebKwr+7C5nbii0sIyi0yOgFV9MRoMbui4iyvRsWahVeCqokL5DCEKgnHKSKvC7FjlOhwWb63h4lE1k5qa1GNKSeGB+CLJIw6SDir9zhUk15bu0E38BupDwCvJ67lv/OKI=,iv:nB+cMJkT7nMbS9cPfFmd3srAV9rHeDfJBtSUDgqlhM0=,tag:ZTOS0UZKTtZD8oYckEaVmw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
