apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:c1WF7Dxij4XazxgCKY2vndBLpA0xepvn1SduosFq4Y/GDAY65fnl6g==,iv:CBYS2lsP653e6VkaeGYQH4tNrTl9NQ57hMmEF+SnDWo=,tag:FSvlQg24uc4L/ybrYtODRA==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRXhqY2FwMzhWVExqVk11
        YVZqUGlkTU5haUF4a3NBVUw2WDhCSnJsTHcwCkRHR3Q5QUthRGJ1TStIRW9qRXB5
        OWxwa2hjMTBKWTBlR3NOaGV0ZnRoa0UKLS0tIDAwU2h6UjNDOENYK1l6NWEvelpF
        UVBUMGNvU2VHWU9STU9SaFJJSkNIc1UKF9xaCQr22NnFqvBr1hwGZEN+3MU16Fsd
        HTCA15txhZSMGCp70AbFj4YOAZ4nqaabfxs9pv9bk1S0ykVLtVAqCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-14T13:21:32Z"
  mac: ENC[AES256_GCM,data:xmEQIg4HOi23Ex0NlYj3BHNR9NOykBA4IKou6yZradhe7KTLxpBsjG7XBe8EiECEaOm7K0hVx6KiizGkDm/pVJkDfB8yFCz0FZt3ha+HB8l/nKlRiUeuGDxYoCnOU7bUb7i3sMx/6oveyUm90wPl/1DepkM/vTUfeC5VusRZv7g=,iv:mBJ5yUi/4aXYc8LaBhoJXkPRHaJc4patdd0d6mxhRfE=,tag:4BcIw5AfhYG6FbusQTnARQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
