apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:04nwY9SI0rxI,iv:iJESxN64k/fOb984mhkT54DhiWhcHS+8kmdVh3CRSfI=,tag:fHm8SPh24rHKZ7amk3lOyg==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SWlyZTJpSjFDT01aSHh1
        eGRscVpCclZ2SFBBZk52ektVQ2N0Q3JrVW5JCllVcE9wTU1UTnZPNDdFQTdzWjF2
        UTRKb0hRRDc2QjU5M0pkMkxJTTZjZ0UKLS0tIDU2aTVqRzJRdysvOUNPd0VHY2R3
        UWR6VVpYWi9qY2xkVTRoRVNqeEtTQVkK9mUmLFyW9G8dClc0u+tTnGHSL1Hr0hFy
        sEmlO+Jlao0Hd9Z0z2vXtygNMilzOD0Pogtypi5ggwuyQm9BPX2zKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-14T13:21:32Z"
  mac: ENC[AES256_GCM,data:u9eQuIov6kicBg6SJ5Yp03yjSJ0DLb5RXfxsKoNqiJtPiOscZ0GEuQWNcXUMaSSut/SFJ432M+PbrmaWd+OEUGrc6hWfnNA8my53Nv232L2bWpQX8FmlzDBAyhkV16baEocz6yQ5RT+d5pcpYUf4RD7VpBmuQ44ml9beZpAnRCI=,iv:q2DNu8VitrZSozkpSlt+qw0jv9Y7IyTymD14GzB9oiU=,tag:7k0c/RJAs7pS5da55H709Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
