apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:l78c4IVqwzqq,iv:BlUG2RdtXqXwa33dwL2nlz4iYethTcjdV2G5Up+OuUA=,tag:qTQXNH6iheLJMOIKmYHiGQ==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMkZLcGRXNjNkbVBYTTRk
        QXZFb0h1ZW9WU2tUQVBUN0oycW9iU0psaml3CmNOblE5MlROdUYvcFJlOU9Ca2VV
        MmtOeGxTQlNCUXE4cFQ0WEpSNTRjS0EKLS0tIDVWYVp2Z1Z0SlBCc0FkaGNjVnVz
        dStkenNXeUJnQ3FBU2prS1V1RkllTHMKPXNHt5ImF4B53bCkKVzdGwaCSbDKL/ky
        U241EvdjalufYvNRv2qYkDnhmHYhrTw+jSVcy2VdL0DisXE32IDC6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T20:32:34Z"
  mac: ENC[AES256_GCM,data:hwOA52CokKJWueJDIwlhIYqS7hF1KPSMvN8heoyuV+J3hNQwCmMwflXNyGt1hJz1X7rJarsehJtJDJ/UDhiZhsu6slie0kY+Dj8GlIgUzkaVo2NVRzgI5EshXNYbnFZ+kRuhWFyDEHUqTQ7v3RNtBPFpoHAH/1aec3TANHKB0O8=,iv:qd7ATseUnQphm7VVYuPPL2kpLCGUASxE56ieRxvdtyg=,tag:e6z3vm8Rfr/U+cRsiPHYaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
