apiVersion: v1
kind: Secret
metadata:
  name: smb-creds
  namespace: csi-smb
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:rJYzEuIa,iv:ddzyfPuKzYnuIOkdNxfm/i/EXmSstBAKuT32lrRF1Ow=,tag:dzRQBcqYFW/cnNH4OxdEQA==,type:str]
  password: ENC[AES256_GCM,data:t01FIkn655aNK+s=,iv:RrO+ztZj+OZDlo3UV5sAAQMFBgy0xkP5zAwZu+ZBEzk=,tag:o6hbRyCLwYpnHxecS+Ek5g==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZFUvL0dOTUNTYkRielpL
        WldQVlIwZ1ppVmpGb0FPUE9Oa1ZsZk4vV2h3CjlsalNXN0dtbHJzOWdlQnNTWFZI
        ejB5VmVtelA0U2FzNFN2T2Rwei9QR3MKLS0tIE1yMDFyQnlRbWZoTEN0eTZUY3dU
        S2QxVDZBSmUyeFhud04xYWlYeWF2NDQKVzXvkOBull4/yDLwcs3VjS1LIhDbee3j
        CKGTTAkR6RImtwdZb6jU1Tcsh9TaoSoE3pDKAEQHsrDl4+2q+My0kg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T11:11:38Z"
  mac: ENC[AES256_GCM,data:3SU5n5PvjHkPGI0wERLn1d2PZjr1WdKuIg8F4QcTJeRkv2lenqJ/ljUAaeHQLLbdiNrXKiyug9m9lSLnQAPsuTXcrp2mycI6xtg1hPJgzqi1LyhYaYbse/OyWmlLxBY0oOfZf9KFgZ4Gj+NSya0pFyrCkj6nz8ExsUgGwIGMucQ=,iv:xgenCfOFWchoKnLLZ142rMGLDuXFOboLAXWoeuMKRjM=,tag:HMsyucBmR9VvDb1PO44pXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
