apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:dEDK11JRzldqCEGYyHsZMyVS4x7WLh8nyKdLjyeKj9M=,iv:o8HLg0edKIlHgVXa4L3UgWniUe6+UzPCvIynLBWLNmU=,tag:UwGK/YZB86awZdXg0ag5hg==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SjMrdkJaZWpBb1ZjcHB6
        NHVFQnQzZkNiaVdmYTI2Z044SlNzaE1CYTM4CmpnUmJrZ2s2aCsxcmFBOGRwOE9m
        dTVHUHpaVE9Oa3J2VE1tdlJZOGVUMkkKLS0tIDl3blJpTDNnNWJqZUd3Q0ZUTXEv
        aVFZcEtKOURCUGtrT0NxMXBPd0FQVEEKleCvTlnhm+iRVEBkrOcp8XWQlcPQLVry
        R2lA3P0ezNvrzIKMZpM/iX0Oh56UyOQwLmj1RGi05QS67DCZxfBMYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-14T13:21:32Z"
  mac: ENC[AES256_GCM,data:MR0WJiP0ZXDhXkkgtdz6PyDiQ3mK+7DJDMR4HUGQPwNuKl/adEP+kdXybTbXKTfe8qZR0VLHg53+V10A0Ft7viUw/HRh0snd0sX1ylM6vUB//9T08N9wKgmjJ73cKiC5Frxn8Z1VR2AHOxHjPsuatxAwBLOiOX5JFYsuoCC8r5U=,iv:rOAAZCRbWRhPXefbHdwp/Hg3gjkRMyd4N3Kcc4+dk4w=,tag:Q4uUjKCKMn5brkmYvWEvQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
