apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:kCgsLCvCzRS9za21gRkmA1Oa6yPWYSR9bJ1QbNGiJM0=,iv:CtJtZGVDkA3JZsX55let+jQkKEjeggyNZ576Pd2lgDc=,tag:bPBBEGruEpPgDhV/NZBX8w==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L0JtcEF3TERHVjV6NEdn
        elVWMzMwdHBqVFVlVlRKTFZIaHZvOUtIUmo0CkdhQjRpV3pQWFNHNWtNNGF3aERW
        T3Rzd0xWT2JLbXBEdVNvakhSb3dsakkKLS0tIGsyNDA5YnRQZWtuZThYc1NYcWV3
        anp5SEhKOTVaMjg5Rlk2ZkdxOS8wZDgKYu1LdyIFjhijXLvsE99e+zlZyy4m154q
        DoxX/gvPDaegpdXIyiTiFQahRvl4vkwTLwBN01t8/1uhdfkKMdUILw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T20:32:34Z"
  mac: ENC[AES256_GCM,data:hKBMeYorV9MCg0SxMQdHruD/iqcg02UGIkaVGGpajUFU/GYQra6vxDwcq7h+pzbENmZCUNqq/sWg2gpxQvLnOvqGyP8/GAcltelScBdP4iDH1UJlk0WPD7Dni19/3eHtcRAImmwR6dsjiOeKsvFNfUgbMERtwI7jOLXOIAbZCDk=,iv:6z4c2X3iMMYQkQqtaxUVzkmea4zBZA17PYTgFIMMov4=,tag:S2LHmmBPZInS4Koetz8Vhg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
