apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1P0Jv+5sMJg68RqouU/6/cnvfQeR1Q2QptlRGDxCDkbj/yR8z/k5t+Ep0GXQ4+tCpT/GJc52FDWqYHIMfy0dCuvL7aROcJjCcnep11LN5k7aHQ6uHRAjcoGc46dIIL2aS5sv712edMgjv1RLc1jGahMn+xom3HfGE8tZTcBPqP5KhmshecpeE3lxxL9BxO0baVhoPffPQ5JF1gIU+xGM+Fz6la3XUbCOGXheam+VWDGgVeHT,iv:nBaBd7CkPJ6sB2CvFHaSKcgxC2JIYqqh1M69uQKCdOs=,tag:GT1+WN8vxUJ7Gq18iua2cg==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweHVYdUpqQU5tSUtqOGtn
        RzQ4eVlmaHd6azVrTDZnTys5QUJmVFhlRGdBCnRGSWRGbG1aaW45R0JmRlVUQzYy
        UG5iMmpWeStaVnd0bWUwNENweGc2QU0KLS0tIHduR3gvUnhuMzlZcFUyNnIxcUcy
        cEVZZXFqMFFkUDdSN0ZucU1uMmJIdWcKYb/ELbtseq+55cxiIIxzxkdkA3upHZrN
        6UHx8V+jw1Q4BOgwzyHCA5H8/yNX3VuFMS4Beqm6W8dc1q67MlliCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T20:32:34Z"
  mac: ENC[AES256_GCM,data:oyCB6Mqghe+h82rA5xLLK/d+9O0ndYbUd0Cm0qt1HRLgb8Jl00rD1QNyXd565tFtM8OBRCDjFVIBKd5n1WG6/m+m04yJ0ud938WNzQIbXLHXgFPqb9fL7dKktUQxXr8iI47h2H4tt0MhpJsXbM1N48zPffrl538A1pg7ay7xoTA=,iv:9MKeoFy0/lLLS/534eiNtO2TYGpIFGXffWmodldfYQY=,tag:jqxwYF+uz4AaCHFNAhq5Tg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
