apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:kKH8WJXZ3gH2rcORIelanh+pZeA+au1clgtmtC8TvAeDspTYmxPdwmjLBkzISYnOmDKSkHZ8PBp0NHceiAJH3n+XlQxpFmc6Mq2YP+y93N7Gt2V2ggxxagMathOhYPHlB2cuqrCUQVDuAgOqF1WlafFJ+xhbYh2F6TaqkT+CUn+NaIz0MExmyct7ZfVP3B7VWXc9meStb4GDEteDvbzDejDvtXmOQQYsi5NG3AmKXkgAZ8nl,iv:2i892VOYtC+BxEs2vd0d9jfI5e2hTGZGzJxPj9kk6i4=,tag:X7Q/rpkttAxL++6u0kQtaA==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeGxBbk9nVjNmUXdhdGM5
        TVZLRjdOa0dTZGw3SHlQOFNCQmZWMk5mVkUwCm52cVA2NmJHdUQrU1VYS1BZK2po
        NHZ5S0gxcUMyKzBHcVRwOTdCQnFoT2cKLS0tIEZWU2ZQb052b2pERlBjWUE2RTJ3
        ZGlPY0ZoUU9DQXFHdnRYOWFtQWg2Rk0KVkqccxvlitk0pPTsDHHWhW4mU8xJjYir
        DBY6P86oc854vQj/dC37i330ikc6VLArD2VGojdJ9HwxNxE184TVvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-14T13:21:32Z"
  mac: ENC[AES256_GCM,data:NgcP3dm7TqK7dTC7pCl9tMwSA7M6vECUrl/z7B1FQaK9p+kigIqWTeXzoR5D64KbmryANGw50o+asniqdj0U2PU55li0b6ymEJA+ef+1m6c6QgAZWGUTkPK0wsgHT5dpjILNABmHzDVLssPldQ3iOsKw1Pbvb8m/+5xJRWrpdEU=,iv:xfRRzVSfGLhyylgUQRGROD8syj9X4+NFLlmGIdlyHI0=,tag:s6oZM4oCXmhlHajVI4l4jA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
