apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:hEVEBML0q8oeaVB2fhI3z9JkZsVFnm8PEk7Ipi4mQLYIRkQKD7dzWQ==,iv:dWZxZXgk8gCtUdlcAgJ+eQjzybRaRgXm6p6nFb+8gBk=,tag:4raT5SZSWZRQjTaLGyCtvQ==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXK2pxZkhEN256Y2F2cnFP
        cjZVVkhtUS9ZZWJyeFM5emc1YTRmczA3ZEMwCnBNN09KSFBLL3dGaXNpTCtkSHhs
        YlJpeG12WTlGY1pnNEZXblMxQStNclUKLS0tIHNHTWdKRVFidWlMMFpucVMzdXdt
        SUgvb1hqMTRpWERqTFRWSm5OVElldkUKE4nAzFIrkMlbj5MVnDPEUcm6hSjaM1m2
        1KwwbhzVvrCUlP7dHeHEGGvUjody07Sbi3A3Twwe3Sm5b/Z7crWfZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-28T20:32:34Z"
  mac: ENC[AES256_GCM,data:D0Izgq9KUs/rz/X/+JfmjTCEsFzypJH0xB5cMG4MpmVHWtD/tegkDlXq1tRQmwwcrGmuqND6MLI1Ye4zrNP4h6UleN4HHfVF8rX2M7IO6i1IMhB81BADFnenjMerOtyrR6KdMRnz97sDF3P3exopc1eAeFE/HQ6h3XIU1pPezp0=,iv:cnMWZrpS6TfhcUrhzZ1GXGHqbt26Unh+waw+WhYQ8xo=,tag:p08V2UpQPl+BZY6cM+bqmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
