apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Dp+p0NoCYv9eia7kaWRlmSJ4DEX6nretYzdLlJqDgKhOychE29u1KQ==,iv:Pbkw5IAJv1n7asZ5S+IpnSS70UzjzIInM2YnWYG0odI=,tag:NHXVlQ/fIlYp5Tqzl4BMXw==,type:str]
sops:
  age:
    - recipient: age1dmpngq98hxwc5dxe35nhrjv76efh23hyg3q42marshyce0k0d4msjhk4zd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cG1nT29LbkxvWkVlTTlR
        ZFh1TW9sK3pQNEtWZDg1dXFMdmZEY1hOeDJrCkRRTWhXV083ZFV0dk54cERJajVr
        S0JiZFUxRkNoQnZmYWFtcWRrMXVxSlEKLS0tIHJZVVBnT1JIaEZQc0N0Mi8waE1H
        bjU3M1N2eER1ZjJNR0tyWUxyTW5mRWMKJFnvBzbTtThu2ydK5qb4V4fx6OjBJ9g5
        j11wXr/i9o1spM/JvHb+JVoUBKrmQvcz4e2cfpFQRiehL6Tp9+qPqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-14T13:21:32Z"
  mac: ENC[AES256_GCM,data:K8Db5INLwCcDRswLSk6jdKUWpsNMWopCbeIkDxNFHyedDcjg7na3CpIiHImWsKIcdraPMQEQE9Zq3ruzjtJopAw8IsbMtT0KzP44n6KCl09u4jsuv8Ebwb6InzNK1s25jEAAMULHMJGuf+DLQ3jKhlHvklGkMid3pYJeKx6uqHE=,iv:R0Q1gsf/54oE2il1yLokdWfHKw6hMGKCYPLkY4ENHQw=,tag:7SamvU4OH4fo07kL+5ctSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
